### ISSUE TITLE
Resolve deprecations

### ISSUE THREAD

**Issue by eatrocks** [tuxsudo/react-starter#17]
Output from `npm i` as of 7/18/2016
`npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!`

`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

**Comment by tuxsudo** [comment]
This should be resolved by commit a6fd4847ffdea845ec81b2454046da83ea170fe1
