### ISSUE TITLE
Rename `onLoad` to `onMount` in mount-load for clarity and warn when not present

### ISSUE THREAD

**Issue by eatrocks** [tuxsudo/react-starter#22]
The method passed as `onLoad()` runs during `componentDidMount()` so onMount is more accurate and more descriptive.
Consider also warning when `onMount()` function wasn't provided. It currently just spews `app.js:36276 Uncaught TypeError: this.props.onLoad is not a function`

**Comment by tuxsudo** [comment]
removed HoC for clarity so this doesn't not apply no mo
