### ISSUE TITLE
Node dependencies in tests

### ISSUE THREAD

**Issue by xZarisx** [tuxsudo/react-starter#25]
running the test for a component that depended on react-lazy-component gave this error:

search-alpha/src/app/components/Image/node_modules/react-lazy-component/src/Component.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, PropTypes } from 'react';
                                                             ^^^^^^
SyntaxError: Unexpected token import

**Comment by tuxsudo** [comment]
this is a duplicate of #34
