### ISSUE TITLE
Loading CSS from node_modules does not seem to be working(?)

### ISSUE THREAD

**Issue by cgood92** [tuxsudo/react-starter#41]
I'm using your starter kit, and love it.  But, I'm having the following issue.

A component has the following line: `import gridlayout from 'gridlayout/gridlayout.min.css';`.

When I run `npm run dev`, I get this error:

```
/Users/cgood92/development/github/hapi-swagger-training/client/node_modules/gridlayout/gridlayout.min.css:1
(function (exports, require, module, __filename, __dirname) { .gl,.gl-cell,.gl-scrollview{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}.gl{width:100%}.gl-cell{position:relative;vertical-align:top}@media only screen and (min-width:40em){.gl{display:table;border-collapse:collapse;table-layout:fixed}.gl.gl-vertical{height:100%}.gl > .gl-cell{display:table-cell}.gl.gl-vertical > .gl-cell{display:table-row}.gl .gl-fill{height:100%}.gl .gl-scrollview{position:relative}.gl > .gl-cell > .gl-scrollview > .gl-scrollview-content{position:absolute;top:0;left:0;right:0;z-index:1;height:100%;overflow:auto;-webkit-overflow-scrolling:touch;overflow-scrolling:touch}.gl > .gl-cell > .gl-scrollview:after{content:'*';visibility:hidden}.gl > .gl-cell > .gl-scrollview{display:block;height:100%}.gl.gl-vertical > .gl-cell > .gl-scrollview{position:relative;display:table-cell;height:auto}.gl-
SyntaxError: Unexpected token .
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.defineProperty.value (/Users/cgood92/development/github/hapi-swagger-training/client/dist/server.js:1584:19)
    at __webpack_require__ (/Users/cgood92/development/github/hapi-swagger-training/client/dist/server.js:20:30)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "dev:server"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-starter@1.0.1 dev:server: `better-npm-run dev:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-starter@1.0.1 dev:server script 'better-npm-run dev:server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run dev:server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-starter
npm ERR! There is likely additional logging output above.
```

Ok, so it looks like the post-css is not doing it's job(?) when I include the file in that fashion.  It has found the file correctly, the file has just not been transformed correctly.

However, if I change the import statement to be a relative path like this: `import gridlayout from '../../../../node_modules/gridlayout/gridlayout.min.css';`, it works fine with no problems...

Any thoughts?  I have tried a few of the `postcss-import` config options, including various paths and whatnot, but that doesn't seem to be solving the issue.

**Comment by xZarisx** [comment]
Is gridlayout this gridlayout https://www.npmjs.com/package/gridlayout? Is the component that imports it a custom component or some component from an npm package?

**Comment by cgood92** [comment]
Yes, it is that gridlayout.  And it's a custom component that I built.  

It's curious how I can import the exact same file in 2 different ways and get 2 different results.  The file being loaded is clearly not the issue.  I still have a feeling it has something to do with https://github.com/tuxsudo/react-starter/blob/master/webpack.base.babel.js#L53

**Comment by xZarisx** [comment]
Try using the none min one

**Comment by cgood92** [comment]
Same result.  I tried that already.

Another thing I tried was: copying the file into the same directory, and did `import gridlayout from './gridlayout.min.css';`, and it worked great.  

So again, it's not the file.  The file is fine.  The issue is something else that is weird.

Doesn't work (method 1):
```
import gridlayout from 'gridlayout/gridlayout.min.css';
```

Works (method 2):
```
import gridlayout from '../../../../node_modules/gridlayout/gridlayout.min.css';
```

It's not a huge deal, because I can make method 2 work obviously.  It just seems amateur to have to do it that way.  Doing it the way of method 1 finds the file correctly, as is obvious by the error message (line 2), it just doesn't run it through some part of the pipeline first, and I'm not sure which or why.

**Comment by tuxsudo** [comment]
In your server's webpack config at line 20, add `gridlayout/gridlayout.min.css` to the `whitelist` array and you should be good.

https://github.com/tuxsudo/react-starter/blob/master/webpack.server.babel.js#L20

**Comment by cgood92** [comment]
Completely fixed the problem.  Thank you.  I was not looking in the right place at all.  I hope if anybody else has the same issue, they can find this "issue" and not have to bug you again :) Appreciate your help!

**Comment by tuxsudo** [comment]
👍
