### ISSUE TITLE
Use `PropTypes` from the prop-types package instead of the main package

### ISSUE THREAD

**Issue by eatrocks** [tuxsudo/react-starter#63]
npm warns: Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

`npm run dev` or `npm start` to see the warning.

**Comment by Jarvis1010** [comment]
It looks researching it, react-helmet older than 5.0.3 is causing this. I don't know if v5+ breaks anything from v4

**Comment by Jarvis1010** [comment]
According to the readme.md at https://github.com/nfl/react-helmet:

> Helmet 5 is fully backward-compatible with previous Helmet releases, so you can upgrade at any time without fear of breaking changes. We encourage you to update your code to our more semantic API, but please feel free to do so at your own pace.
